### ISSUE TITLE
this.isPaused is not a function

### ISSUE THREAD

**Issue by KenRmk** [feross/chrome-net#27]
Hello. when using this module with `http-node` in chrome app I'm getting this error
```
Error in response to sockets.tcp.getInfo: TypeError: this.isPaused is not a function
    at Object.chrome.sockets.tcp.getInfo [as callback] (chrome-extension://fnnjmokkdddamgbnohhpdlflaggbmnfd/bundle-http.js:1939:19)
    at Socket._onConnect (chrome-extension://fnnjmokkdddamgbnohhpdlflaggbmnfd/bundle-http.js:1922:26)
    at new Socket (chrome-extension://fnnjmokkdddamgbnohhpdlflaggbmnfd/bundle-http.js:1839:14)
    at Server._onAccept (chrome-extension://fnnjmokkdddamgbnohhpdlflaggbmnfd/bundle-http.js:1749:28)
    at onAccept (chrome-extension://fnnjmokkdddamgbnohhpdlflaggbmnfd/bundle-http.js:1569:32)
```
just by receving request in a simple http server like so
```
import http from 'http-node';
http.createServer(function(req, res) {
	console.log('HTTP request', req.method, req.url);
	res.end();
}).listen(8125);
```

**Comment by jscissr** [comment]
It looks like you're using an old version of stream, see [here](https://github.com/feross/chrome-net/commit/b185179ea98176ca5dff548e2a66491f0724ac07#diff-168726dbe96b3ce427e7fedce31bb0bcL729). Does updating to readable-stream v3 help?

**Comment by KenRmk** [comment]
Yes, you're right. For some reason older readable-stream got installed to my app.

**Comment by avwel** [comment]
For those who are pulling their hair out due to this error "isPaused is not a function" -- when using chromiumify I ran into this. However, when using browserify directly, it pulled in the correct streams module.
